### PR TITLE
feat: consumed (and exposed "via API") type

### PR DESCRIPTION
**Pull request by kivra-pauoli**
## Motivation

Used by [`kivra_core`](https://github.com/kivra/kivra_core/blob/9b9cdd9cca458374047c2de20ac7cac1e13a9785/src/rest/rest_handler.erl#L94).

## Further considerations

I up'ed CI and results are promising. Now going after 24, 25, and 26 😄

### CODE REVIEW

**Comment by kivra-pauoli** [comment]
I'm gonna look at the CI results, but it's strange that it'd break for a "simple" type export 😄

**Comment by kivra-pauoli** [comment]
Oh, yeah, we're using [`gleam-lang/setup-erlang`](https://github.com/gleam-lang/setup-erlang) 😄 It's been archived for around 2 years already. I'll move this over to [`erlef/setup-beam`](https://github.com/erlef/setup-beam).

**Comment by kivra-pauoli** [comment]
Looks like something needs to be changed in the repository settings

image

**Comment by kivra-pauoli** [comment]
I updated the project settings to target CI for 24, 25, and 26 as requirements.

**Review by kivraDawi — APPROVED** [review]

**Pull request merged**
